scverse/rapids_singlecell

rapids_singlecell/cunnData/__init__.py

added default `.obs` and `.var`

added default Dataframe for obs and var

---

pyproject.toml
rapids_singlecell/__init__.py
rapids_singlecell/cunnData/__init__.py

* fixes a bug with `_inplace_subset_obs`
* removed `tests` from distributions

_inplace_subset_obs fix

---

rapids_singlecell/scanpy_gpu/_harmonpy_gpu.py

Fixes a bug where larger datasets with harmony failed

Fix for Harmony_GPU that enables larger Datasets

---

.github/workflows/test-gpu.yml

Fail GPU job as intended

---

docs/api.md
pyproject.toml
src/rapids_singlecell/scanpy_gpu/__init__.py
src/rapids_singlecell/scanpy_gpu/_umap.py

* added in umap support
* made scanpy a dependency

added umap support

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/submit-question.md

added issue templates

---

src/rapids_singlecell/cunnData_funcs/_simple.py

Fixes a small issue where pre-commit would break the function.

small fix for filter_highly_variable

---

docs/api.md

added neighbors

---

pyproject.toml

remove anndata-rc

---

docs/release-notes/0.9.2.md
docs/release-notes/index.md
src/rapids_singlecell/preprocessing/_neighbors.py
src/rapids_singlecell/tools/_umap.py

Neighbors & umap fix

---

.pre-commit-config.yaml
pyproject.toml
src/rapids_singlecell/decoupler_gpu/_method_mlm.py
src/rapids_singlecell/decoupler_gpu/_method_wsum.py
src/rapids_singlecell/preprocessing/_regress_out.py

Remove black infavor of ruff

---

src/rapids_singlecell/preprocessing/_pca.py

adds in params for pca. fixes #90

adds params

---

README.md
ci/rsc_test_env.yml
conda/rsc_rapids_23.10.yml
docs/Installation.md
docs/conf.py
docs/release-notes/0.9.3.md
docs/release-notes/index.md
src/rapids_singlecell/preprocessing/_neighbors.py
tests/test_neighbors.py

This moves from cuml to Raft for the approximate NN search.

changed neighbors to raft

---

pyproject.toml

fixes CI and installs

---

docs/release-notes/0.9.4.md
src/rapids_singlecell/preprocessing/_kernels/_norm_kernel.py
src/rapids_singlecell/preprocessing/_normalize.py

This implementation is a bit faster than the standard cupy implementation
#111

added kernel for sparse sum along major axis

---

docs/release-notes/0.10.0.md
src/rapids_singlecell/tools/_clustering.py

changed graph creation

---

docs/release-notes/0.10.0.md
src/rapids_singlecell/preprocessing/_harmony_integrate.py
src/rapids_singlecell/preprocessing/_harmonypy_gpu.py
src/rapids_singlecell/preprocessing/_utils.py

This will make harmony run with 32 as an option

Add option to make harmony 32 bit

---

docs/release-notes/0.10.0.md
src/rapids_singlecell/preprocessing/_hvg.py
src/rapids_singlecell/preprocessing/_normalize.py
src/rapids_singlecell/preprocessing/_scale.py
src/rapids_singlecell/preprocessing/_utils.py
tests/test_hvg.py

Adds a check for sparse canonical format to some functions.

Add canonical format check

---

docs/api/scanpy_gpu.md
docs/release-notes/0.9.1.md
pyproject.toml
src/rapids_singlecell/preprocessing/_scrublet/__init__.py
src/rapids_singlecell/tools/_diffmap.py

Release 0.10.0

---

.github/workflows/publish.yml
.github/workflows/test-gpu.yml

updates the github action versions

updates action versions

---

docs/release-notes/0.10.1.md
src/rapids_singlecell/preprocessing/_scale.py
tests/test_scaling.py

In scale clipping was applied to the whole array. no its only the masked part.

updates clip to work with masks

---

docs/release-notes/0.10.2.md
src/rapids_singlecell/get/_aggregated.py
src/rapids_singlecell/get/_kernels/_aggr_kernels.py
tests/test_aggregated.py

Adds sparse sparse to aggregate

---

docs/release-notes/0.10.3.md
src/rapids_singlecell/preprocessing/_scale.py

use `cp.clip` for clipping in `pp.scale`

use cp.clip

---

docs/release-notes/0.10.3.md
src/rapids_singlecell/preprocessing/_kernels/_scale_kernel.py
src/rapids_singlecell/preprocessing/_scale.py

This updates scale to use rawkernels. These kernel are important for the later dask implementation

updates scale use kernels

---

docs/release-notes/0.10.3.md
src/rapids_singlecell/squidpy_gpu/_gearysc.py
src/rapids_singlecell/squidpy_gpu/_moransi.py

updates autocorr to reuse allocations

use prealloc

---

docs/release-notes/0.10.5.md
src/rapids_singlecell/preprocessing/_hvg.py
tests/test_hvg.py

fixes csc matrix for seurat_v3

fixes a small bug for seurat_v3 with csc matrix

---

docs/release-notes/0.10.5.md
src/rapids_singlecell/_utils/__init__.py
src/rapids_singlecell/preprocessing/_scrublet/__init__.py
src/rapids_singlecell/preprocessing/_scrublet/core.py
src/rapids_singlecell/preprocessing/_scrublet/pipeline.py
src/rapids_singlecell/preprocessing/_scrublet/sparse_utils.py

add AnyRandom

---

docs/release-notes/0.10.7.md
docs/release-notes/index.md
src/rapids_singlecell/preprocessing/_kernels/_sparse2dense.py
src/rapids_singlecell/preprocessing/_pca.py
src/rapids_singlecell/preprocessing/_scale.py
src/rapids_singlecell/preprocessing/_utils.py

updates densification for sparse matrices

sparse2dense fast

---

src/rapids_singlecell/preprocessing/_kernels/_sparse2dense.py

This fixes potential memory issues with sparse2 dense

fix kernel

---

src/rapids_singlecell/preprocessing/_qc.py
src/rapids_singlecell/preprocessing/_sparse_pca/_dask_sparse_pca.py
src/rapids_singlecell/preprocessing/_utils.py

Cleaner, next will be `qc` which is giving issues

(feat): use `map_blocks` in gram matrix calculation and and `mean_var`

---

docs/release-notes/0.10.9.md
pyproject.toml
src/rapids_singlecell/preprocessing/_pca.py
src/rapids_singlecell/tools/_tsne.py
src/rapids_singlecell/tools/_umap.py

Add key_added parameter to pca, tsne and umap

---

docs/release-notes/0.10.11.md
src/rapids_singlecell/preprocessing/_kernels/_bbknn.py
src/rapids_singlecell/preprocessing/_neighbors.py
tests/test_neighbors.py

add trimming to bbknn

---

docker/Dockerfile
docker/Dockerfile.deps
docs/release-notes/0.10.11.md

Aims on fixing [this issue](https://github.com/scverse/rapids_singlecell/issues/291)

Remove ENTRYPOINT overrides from Dockerfiles

---

.readthedocs.yml
docker/docker-push.sh
docs/release-notes/0.10.11.md
pyproject.toml

0.10.11 release

---

docs/conf.py
docs/release-notes/0.10.12.md
src/rapids_singlecell/preprocessing/_neighbors.py

add support for cuvs in next version of rapids

update to use cuvs for next rapids

---

docs/release-notes/0.12.1.md

* update kmeans and leiden
* add n_init to harmony
* add kmeans test

update clustering (#338)

---

src/rapids_singlecell/squidpy_gpu/_co_oc.py

Is there a reason why you want to keep this print? I guess it's an oversight?

Remove print in CO

---

src/rapids_singlecell/squidpy_gpu/_co_oc.py
src/rapids_singlecell/squidpy_gpu/kernels/_co_oc.py

Update co oc kernel

---

src/rapids_singlecell/get/_anndata.py

add documentation for get

---

docs/release-notes/0.12.6.md
docs/release-notes/index.md
src/rapids_singlecell/tools/_clustering.py
tests/test_clustering.py

Allow for clustering with louvain and leiden to use 64 bit weights

Clustering 64 bit
